name: utilize
channels:
  - openeye
  - conda-forge
  - omnia
  - defaults
dependencies:
  - ambermini=16.16.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - boost=1.68.0
  - boost-cpp=1.68.0
  - bson=0.5.8
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.16.0
  - certifi=2019.3.9
  - decorator=4.4.0
  - fftw3f=3.3.4
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - icu=58.2
  - importlib_metadata=0.18
  - jpeg=9c
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgfortran=3.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - more-itertools=4.3.0
  - msgpack-python=0.6.1
  - ncurses=6.1
  - networkx=2.3
  - numpy=1.16.4
  - olefile=0.46
  - openblas=0.3.5
  - openeye-toolkits=2019.4.2
  - openforcefield=0.4.0
  - openmm=7.3.1
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - parmed=3.2.0
  - pcre=8.41
  - pillow=6.0.0
  - pip=19.1.1
  - pixman=0.34.0
  - pluggy=0.12.0
  - pthread-stubs=0.4
  - py=1.8.0
  - pycairo=1.18.1
  - pyparsing=2.4.0
  - pytest=4.6.3
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1.1
  - rdkit=2019.03.2
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.9
  - toml=0.10.0
  - wcwidth=0.1.7
  - wheel=0.33.4
  - xmltodict=0.12.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zipp=0.5.1
  - zlib=1.2.11
  - zstd=1.4.0
